- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'Hi, this is from command module' > /tmp/command.txt"

  - name: shell module
    ansible.builtin.shell: "echo 'Hi, this is from shell module' > /tmp/shell.txt" 

    #command.txt is not created for above task (reason can be seen in readme.MD)
    # whatever works in command module, it will work in shell module, but vice versa is not true. 

