- name: conditions
  hosts: local
  become: yes
  tasks:
  - name: user exist or not
    ansible.builtin.command: dscl . -read /Users/username
    register: USER
    ignore_errors: true


  - name: say hello
    ansible.builtin.debug:
      msg: "Hello"
