- name: variable preference
  hosts: localhost
  vars:
   WISHES: morning-from-play
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: WISHES
    prompt: Enter wishes
    private: false
   
  tasks:
  - name: variable from play
    vars:
     WISHES: morning-from-task
    ansible.builtin.debug:
     msg: Hello! Good {{WISHES}}