- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Enter username
    private: false
  - name: PASSWORD
    prompt: Enter Password
    private: true

  tasks:
  - name: using variable from prompt
    ansible.builtin.debug:
     msg: username is {{USERNAME}} . password is {{PASSWORD}}
