- name: variable preference
  hosts: localhost
  vars_prompt:
  -name: WISHES
   prompt: Enter wishes
   privare: false
  vars:
   WISHES: morning-from-play 
  tasks:
  - name: variable from play
    vars:
     WISHES: morning-from-task
    ansible.builtin.debug:
     msg: Hello! Good {{WISHES}}