- name: variables from arguments
  hosts: localhost
  tasks:
  - name: get from args
    ansible.builtin.debug:
     msg: Hello {{PERSON}}, Good {{WISHES}} #when we want to give variable as arguments when running the file we need to pass as below:
     #ansible-playbook vars-args-09.yaml --extravars "PERSON=ramesh WISHES=Morning" or
     #ansible-playbook vars-args-09.yaml -e PERSON=ramesh -e WISHES=Morning
