- name: variable preference
  hosts: localhost #for executing on windows
  # hosts: local #for executing on mac
  # connection: local #for executing on mac
  vars:
   WISHES: morning-from-play
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: WISHES
    prompt: Enter wishes
    private: false
   
  tasks:
  - name: variable from play
    vars:
    WISHES: morning-from-task
    ansible.builtin.debug:
     msg: Hello! Good {{WISHES}}

     #1.first variable executed from args
     #2. executed from task
     #3.executed from file
     #4.prompt
     #5.play
     #6.inventory